project:
  type: website
  output-dir: docs

lang: ko

website:
  title: "IR"
  site-url: https://ir-handong.github.io
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: 홈
      - href: about.qmd
        text: 소개
    right:
      - icon: github
        href: https://github.com/ir-handong
  page-footer:
    center: "&copy; 2026 IR Handong. All rights reserved."

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
